Add user_level to confirm the attributes be changed at least by admin/manager Fix spec
/app/views/notification_mailer/activate_staff_account.text.erb:19
Error: <%= user_from_callbacks_staff_accounts_url(token: @staff_account.token) %>
     ActionView::Template::Error:
       Missing host to link to! Please provide the :host parameter, set default_url_options[:host], or set :only_path to true